prompt_order = [
    'username',
    'hostname',
    'directory',
    'git_branch',
    'git_commit',
    'git_state',
    'git_status',
    'hg_branch',
    'package',
    'dotnet',
    'golang',
    'java',
    'nodejs',
    'php',
    'python',
    'ruby',
    'rust',
    'terraform',
    'nix_shell',
    'conda',
    'memory_usage',
    'aws',
    'env_var',
    'kubernetes',
    'cmd_duration',
    'line_break',
    'jobs',
    'battery',
    'time',
    'character',
]

[hostname]
ssh_only = true
prefix = ' '
suffix = ' $BG[255]%F{105}'
style = 'bg:105 fg:104 '
trim_at = ''
disabled = false

[directory]
prefix = '$BG[256] '
suffix = '$BG[256] '
style = 'bg:white fg:black bold'

[kubernetes]
symbol = ' '
style = 'bg:255 blue'
disabled = true
suffix = '$BG[255] $reset_color%F{255}'
prefix = ' %F{255}$BG[255]'

[aws]
disabled = true

[git_branch]
symbol = ' '
suffix = '$BG[106] '
prefix = '$BG[106]%F{231} '
style = 'bg:106 white'

[git_commit]
disabled = false
commit_hash_length = 4
style = 'bg:106 white'
prefix = ' '
suffix = ' $reset_color%F{106}'

[git_status]
style = 'green'
modified = ' • '
prefix = ' '
suffix = ' '
stashed = ' '
show_sync_count = true

[rust]
disabled = true
symbol = ' ⚙️ '

[package]
symbol = ' 📦 '
disabled = true

[character]
style_success = 'black'
symbol = '%F{107}❯▸ '

[nodejs]
prefix = ' '

[time]
prefix = ' '
