prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "kubernetes",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

[hostname]
ssh_only = true
prefix = " "
suffix = " $BG[234]%F{218}"
style = "bg:218 fg:236 bold"
trim_at = ""
disabled = false

[directory]
prefix = "$BG[234] "
suffix = "$BG[234] $BG[236]%F{234}"
style = "bg:234 fg:blue bold"

[kubernetes]
symbol = " "
style = "bg:234 blue"
disabled = false
suffix = "$BG[234] $reset_color%F{234}"
prefix = " %F{234}$BG[234]"

[aws]
disabled = true

[git_branch]
symbol = " "
suffix = "$BG[236] "
prefix = " "
style = "bg:236 yellow"

[git_commit]
disabled = false
commit_hash_length = 4
style = "bg:236 yellow"
prefix = " "
suffix = " $reset_color%F{236}"

[git_status]
style = "yellow"
modified = " • "
prefix = " "
suffix = " "
stashed = " "
show_sync_count = true

[rust]
disabled = true
symbol = " ⚙️ "

[package]
symbol = " 📦 "
disabled = true

[character]
style_success = "magenta"
symbol = "%F{magenta}❯ "

[nodejs]
prefix = " "
