[directory]
style = 'fg:75 bold'

[hostname]
ssh_only = true
disabled = false

[shell]
style = 'yellow bold'

[kubernetes]
disabled = false
style = 'blue'
format = '[$context \($namespace\)](green) '

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = ' '
style = 'yellow'

[git_commit]
disabled = false
commit_hash_length = 4
style = 'yellow'

[git_status]
style = 'yellow'
modified = ' • '
stashed = ' '
ahead = ' ⇡$count '
behind = ' ⇣$count '

[package]
symbol = ' 📦 '
disabled = true

[battery]
disabled = true

[c]
disabled = true
