[hostname]
ssh_only = true
disabled = false

[kubernetes]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = ' '
style = 'cyan'

[git_commit]
disabled = false
commit_hash_length = 4
style = 'cyan'

[git_status]
style = 'yellow'
modified = ' • '
stashed = ' '
ahead = ' ⇡ $count '
behind = ' ⇡ $count '

[package]
symbol = ' 📦 '
disabled = true
