# ZSH, ZSH_DOTS

plugins=(
  docker
  docker-compose
  git
  # fzf
  zsh-completions
  zsh-autosuggestions
)

source ~/.profile
source ~/.zprofile

source $ZSH/oh-my-zsh.sh
source $ZSH_DOTS/path.sh
source $ZSH_DOTS/conf.sh
source $ZSH_DOTS/alias.sh
