# ZSH, ZSH_DOTS

ZSH_THEME="x-refined"

plugins=(
  docker
  docker-compose
  git
  fzf
  zsh-completions
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh
source $ZSH_DOTS/path.sh
source $ZSH_DOTS/conf.sh
source $ZSH_DOTS/alias.sh
source ~/.profile
